-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtiE8iVkV5WySWlPc
YWI0GLh9OqwXtq5mEg+AHJ0yLeGgCgYIKoZIzj0DAQehRANCAAQSXur3CNSNJ+XY
9WEuMemVU5HjdO/g5dVNtsB6/+DSUVPZnH+BiLl/0CUgRb/GWcUcRF5BfQzOhqfm
6qSpnOVs
-----END PRIVATE KEY-----